// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practice.Context;

#nullable disable

namespace practice.Migrations
{
    [DbContext(typeof(GeneralContext))]
    [Migration("20230503124732_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("practice.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            ClassName = "Math",
                            StudentID = 0
                        },
                        new
                        {
                            ClassID = 2,
                            ClassName = "Science",
                            StudentID = 0
                        });
                });

            modelBuilder.Entity("practice.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            ClassID = 1,
                            StudentAddress = "Eskişehir",
                            StudentName = "Cemtuğ Kaan",
                            StudentSurname = "Taşan"
                        },
                        new
                        {
                            StudentID = 2,
                            ClassID = 1,
                            StudentAddress = "My Heart",
                            StudentName = "Burcu",
                            StudentSurname = "Taşan"
                        },
                        new
                        {
                            StudentID = 3,
                            ClassID = 2,
                            StudentAddress = "Siirt",
                            StudentName = "Hakan",
                            StudentSurname = "Balamir"
                        },
                        new
                        {
                            StudentID = 4,
                            ClassID = 2,
                            StudentAddress = "İstanbul",
                            StudentName = "Uğur",
                            StudentSurname = "Demir"
                        });
                });

            modelBuilder.Entity("practice.Models.Student", b =>
                {
                    b.HasOne("practice.Models.Class", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("practice.Models.Class", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
